information:
  - "Safeguard is a plugin to keep your server safe against potential threats."
  - ""
  - "Features"
  - "- VPN / Poxy Protection"
  - "- Fraud Score Detection (Reduce risks of chargebacks)"
  - "- Player captcha"
  - ""
  - "All data is gathered from IPQualityScore API."
  - "Create an account at https://www.ipqualityscore.com to get your API key."
  - "Limit of 5,000 checks/month on the free plan."

api_key: ""
mcleaks_api_key: ""

options:
  prevent_vpn: true
  prevent_proxy: true
  prevent_high_fraud_score: true
  captcha_enabled: true
  allow_fraud_score_less_than: 50
  captcha_gui_title: "&b&lSafeGuard Captcha"

permissions:
  staff_notify: "safeguard.notify"
  vpn_proxy_fraud_bypass: "safeguard.ip.bypass"
  captcha_bypass: "safeguard.captcha.bypass"
  reload_command: "safeguard.reload"
  help_command: "safeguard.reload"

messages:
  vpn_kick: "&c&l[!] &7Your IP address is connected to a VPN provider.\nPlease disable any &cVPN/Proxy&7 to connect to the server."
  proxy_kick: "&c&l[!] &7Your IP address is connected to a proxy provider.\nPlease disable any &cVPN/Proxy&7 to connect to the server."
  fraud_score_kick: "&c&l[!] &7Your IP address is connected to a high fraud score.\nYour connection to the server was cancelled."
  mcleaks_kick: "&cThis account is compromised.\nAppeal at www.server.com."
  vpn_notify: "&b&l[SafeGuard] &3&n%player%&r &7tried to connect with a VPN. Connection cancelled."
  proxy_notify: "&b&l[SafeGuard] &3&n%player%&r &7tried to connect with a proxy. Connection cancelled."
  fraud_score_notify: "&b&l[SafeGuard] &3&n%player%&r &7tried to connect with a high fraud score. Connection cancelled."